## Configuration for the training, evaluation
## Configuration for the training, evaluation
samples:


  - name: 4top
    label: 1

    path: /store/hep/users/jhgoh/nurion4hep/20211211_1/graph/8285877F-4B82-6B4B-BDD2-CDBABE12443D.h5

    xsec: 0.012
    ngen: 11952188

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.0, 0.0] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
