## Configuration for the training, evaluation
samples:
  - name: QCD700
    label: 0
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT700*/*.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT700*/*.h5
    xsec: 6330
    ngen: 48158738
  - name: QCD1000
    label: 0
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT1000*/*.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT1000*/*.h5
    xsec: 1090
    ngen: 14353647
  - name: QCD1500
    label: 0
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT1500*/*.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT1500*/*.h5
    xsec: 99.1
    ngen: 112873
  - name: QCD2000
    label: 0
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT2000/*.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT2000/*.h5
    xsec: 20.2
    ngen: 10955087

  - name: ttbar
    label: 1
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_h5/*.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_h5/*.h5
    xsec: 377.96
    ngen: 333332000
    
  - name: 4top
    label: 2
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/4top_h5/*/*.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/4top_h5/*/*.h5
    xsec: 0.012
    ngen: 11952188


training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
