## Configuration for the training, evaluation
samples:
  - name: QCD700
    label: 0
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT700_1/*-2.h5
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT700_1/*1.h5
    xsec: 6330
    ngen: 48158738
    ####98833
  
  - name: QCD1000
    label: 0
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT1000/*-2.h5
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT1000/*1.h5
    xsec: 1090
    ngen: 14353647
    #####78290
  
  - name: QCD1500
    label: 0
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT1500/*-2.h5
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT1500/*1.h5
    xsec: 99.1
    ngen: 10955087
    #####112873
  
  - name: QCD2000
    label: 0
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT2000/*-2.h5
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT2000/*1.h5
    xsec: 20.2
    ngen: 5475677
    #####76483
  
  - name: ttbar
    label: 1
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_h5/*_64*_0.h5
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_h5/*1_0.h5
    xsec: 377.96
    ngen: 333332000 
    ####2286310
  
  - name: 4top
    label: 2
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/4top_h5/ex1_v2/*1.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/4top_weight_210709/*/*.pt
    xsec: 0.012 
    ngen: 11952188
    #####2849104

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
