## Configuration for the training, evaluation
samples:
  - name: QCD700
    label: 0
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT700_1/*-2.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT700_1/*1.h5
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_h5/HT700_1/QCD_HT700_1-2018-9.h5
    xsec: 6330
    ngen: 48158738

  
  - name: ttbar
    label: 1
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_h5/*_64*_0.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_h5/*1_0.h5
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_h5/ttbar_999_0.h5
    xsec: 377.96
    ngen: 333332000 
  


training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
