## Configuration for the training, evaluation
samples:
  - name: ttbar
    label: 0
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_h5/*.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_h5/*.h5
    xsec: 377.96
    ngen: 33332000 
  - name: 4top
    label: 1
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/4top_h5/*/*.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/4top_h5/*/*.h5
    xsec: 0.012
    ngen: 11952188

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
