## Configuration for the training, evaluation
## Configuration for the training, evaluation
samples:


  - name: 4top
    label: 1
#     path: /store/hep/users/jhgoh/nurion4hep/20211116_1/graph/*.h5
    # path: /store/hep/users/yewzzang/4top_lhe/4top/FCD0B4D1-E7D1-004A-B5AB-131A37EF1928.h5
#     path: /store/hep/users/jhgoh/nurion4hep/20211116_1/graph/9CED6751-B459-1442-AB96-EE3FB4F6E268.h5
    path: /store/hep/users/jhgoh/nurion4hep/20211211_1/graph/FFCC1D28-13A5-BE47-86C9-FC96B6D855B4.h5
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/4top_h5/*/*.h5
    xsec: 0.012
    ngen: 11952188

training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
