## Configuration for the training, evaluation
samples:
  - name: QCD700
    label: 0
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_weight_210709/HT700*/*.pt
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_alledge/HT700*/*.pt
    xsec: 6330
    ngen: 48158738
  - name: QCD1000
    label: 0
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_weight_210709/HT1000*/*.pt
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_alledge/HT1000*/*.pt
    xsec: 1090
    ngen: 14353647
  - name: QCD1500
    label: 0
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_weight_210709/HT1500*/*.pt
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_alledge/HT1500*/*.pt
    xsec: 99.1
    ngen: 112873
  - name: QCD2000
    label: 0
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_weight_210709/HT2000/*.pt
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/QCD_alledge/HT2000/*.pt
    xsec: 20.2
    ngen: 10955087

  - name: ttbar
    label: 1
    path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_weight_210719/*.pt
#     path: /store/hep/users/yewzzang/4top_QCD_ttbar/data_graph/pt/ttbar_alledge/*.pt
    xsec: 377.96
    ngen: 333332000 


training:
    randomSeed1: 12345
    nDataLoaders: 4

    splitFractions: [0.6, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-4
